server:
  port: 8080
  servlet:
    context-path: "/data/check"

spring:
  profiles:
    active: dev
  datasource: #多数据源配置
    url: jdbc:mysql://localhost:3306/check?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: du123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    connection-init-sqls: set names utf8mb4;
    maximum-pool-size: 25
    minimum-idle: 5
  redis:
    timeout: 30000
    jedis:
      pool:
        max-active: 500
        max-wait: 1500
        max-idle: 200
        min-idle: 10
        max-total: 5000
    sentinel:
      master: mymaster
      nodes: 172.16.248.40:26379,172.16.248.41:26379,172.16.248.42:26379

bloom:
  filter:
    size: 200
    fpp: 0.02




